timezone: America/Los_Angeles
encoding: utf-8
url: "https://seyonec.com"
title: "Seyone Chithrananda"
description: "Seyone Chithrananda is a Stanford Bioengineering PhD student working on machine learning for metagenomic discovery and tools to discover and engineer molecular function."
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
collections:
  posts:
    permalink: /blog/:slug:output_ext
# github defaults
lsi: false
safe: true
source: .
incremental: false
gist:
  noscript: false
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
